authz/urls.py
from . import views
from django.urls import path
app_name = 'authz'
urlpatterns = [
    path('', views.Login.as_view(), name="login"),
    path('login/', views.Login.as_view(), name="login"),
    path('logout/', views.logout, name="logout"),
    path('register/', views.Register.as_view(), name="register")
]

crmv1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authz.urls')),
    path('tasks/', include('tasks.urls'))
]

tasks/new_task/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('',
         views.NewTask.as_view(), name="new-task")
]

tasks/review_task/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('',
         views.ReviewTask.as_view(), name="review-task"),
    path('changeStatus',
         views.changeStatus, name="change-status")
]

tasks/urls.py
# URLS FOR TASKS
from django.urls import path, include
from . import views
app_name = 'tasks'

urlpatterns = [
    path('', views.TaskList.as_view(), name="task-list"),
    path('<int:taskid>/', views.task, name="task"),
    path('delete-product/', views.delete_product, name="delete-product"),
    path('new-task/', include('tasks.new_task.urls')),
    path('<int:taskid>/add-products/',
         include('tasks.add_products.urls')),
    path('<int:taskid>/workon-task/', include('tasks.workon_task.urls')),
    path('<int:taskid>/review-task/', include('tasks.review_task.urls')),
    path('<int:taskid>/upload-task/', include('tasks.upload_task.urls'))
]

tasks/workon_task/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('',
         views.WorkonTask.as_view(), name="workon-task"),
    path('mark-as-complete',
         views.MarkComplete.as_view(), name="mark-as-complete")
]

tasks/add_products/models.py
from django.db import models

# Create your models here.

tasks/new_task/models.py
from django.db import models

# Create your models here.

tasks/review_task/models.py
from django.db import models

# Create your models here.

tasks/upload_task/models.py
from django.db import models

# Create your models here.

tasks/workon_task/models.py
from django.db import models

# Create your models here.

tasks/add_products/views.py
import json
import pickle
from woocommerce import API
from django.shortcuts import render, HttpResponse
from tasks.models import Task, Product
from django.http import Http404
from django.views import View
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


# Create your views here.

filepath = "superman"
fetched_data = ""
with open(filepath, 'rb') as inFile:
    fetched_data = pickle.load(inFile)
    inFile.close()
# print(fetched_data)
fetched_data = fetched_data['upload_secrets']


@method_decorator(login_required, name="dispatch")
class AddProducts(View):
    def get(self, request, taskid):

        try:
            task = Task.objects.get(id=taskid)
            # print(task.status)

            if request.user == task.given_by:
                if task.status != Task.NEW:
                    return HttpResponse("Products already added", 405)
            else:
                return HttpResponse("You cannot add products!!", 401)
        except Task.DoesNotExist:
            return HttpResponse("Task does not exist", 404)
        try:
            rootLevelParents, secondLevelParents = getCategories()
        except KeyError:
            return HttpResponse("API credentials are not working", 200)
        context = {
            "rootLevelParents": rootLevelParents,
            "secondLevelParents": secondLevelParents,

        }

        if 'category' in request.GET:
            catId = request.GET['category']

            simpleProducts, variableProducts, variationProducts = getCatProd(
                catId)
            already_added_products = list(Product.objects.values_list(
                'product_id', flat=True).filter(task_id=taskid))
            # print(already_added_products)
            context = {
                "rootLevelParents": rootLevelParents,
                "secondLevelParents": secondLevelParents,
                "variableProducts": variableProducts,
                "variationProducts": variationProducts,
                "simpleProducts": simpleProducts,
                "already_added_products": already_added_products
            }

        return render(request, "add-products.html", context)

    def post(self, request, taskid):
        product_ids = request.POST.getlist("product_ids")
        # print("received for assigning to the task - {}:\n".format(product_ids))
        # print("iskey baad")
        # for e in request.POST:
        #     print(e)
        already_added_products = list(Product.objects.values_list(
            'product_id', flat=True).filter(task_id=taskid))
        asssigned_prod = len(product_ids)
        for product_id in product_ids:
            # print("product_id - ", product_id)
            task = Task.objects.get(pk=taskid)
            if product_id in already_added_products:
                asssigned_prod -= 1
                continue
            else:
                regular_price = request.POST.get("regular_price_"+product_id)
                # print("regular price", regular_price)
                try:
                    regular_price = float(request.POST.get(
                        "regular_price_"+product_id, 0.0))
                except ValueError:
                    regular_price = None
                    # print("value error!")
                except TypeError:
                    regular_price = None
                    # print("type error!")

                try:
                    sale_price = float(request.POST.get(
                        "sale_price_"+product_id, 0.0))
                except ValueError:
                    sale_price = None
                    # print("value error!")
                except TypeError:
                    sale_price = None
                    # print("type error!")

                product = Product.objects.create(
                    product_id=product_id,
                    name=request.POST.get("name_"+product_id),
                    regular_price=regular_price,
                    sale_price=sale_price,
                    # curr_price=curr_price,
                    task_id=task,
                    last_modified_by=request.user,
                    last_mod_onsite=request.POST.get(
                        "last_mod_onsite_"+product_id),
                    parent_id=request.POST.get("parent_"+product_id),
                    permalink=request.POST.get("permalink_"+product_id)
                )
                product.save()

        return HttpResponse("Successfully assigned " + str(asssigned_prod) + " products")


def getCategories():
    wcapi = API(
        url=fetched_data['url'],
        consumer_key=fetched_data['consumer_key'],
        consumer_secret=fetched_data['consumer_secret'],
        version=fetched_data['version']
    )

    catResp = wcapi.get("products/categories?per_page=100")
    # print("===== catresp headers===")
    # for el in catResp.headers:
    #     print(el)

    totalPages = catResp.headers['X-WP-TotalPages']

    totalCat = int(catResp.headers['X-WP-Total'])
    rootLevelParents = []
    secondLevelParents = []
    catWoRoot = []
    # cat id rom the form submit
    # find rootLevelParents
    for nextPage in range(2, int(totalPages)+2):
        for cat in catResp.json():
            if cat['parent'] == 0:
                # print(cat['name'])
                rootLevelParents.append((cat['id'], cat['name']))
            else:
                catWoRoot.append(
                    (cat['id'], cat['name'], cat['parent']))
        catResp = wcapi.get(
            "products/categories?per_page=100&page={}".format(nextPage))

    # print("total cat", totalCat)
    # print("root cat", len(rootLevelParents))
    # print("cat wo root", len(catWoRoot))

    # find secondLevelParents
    for catRow in catWoRoot:
        for rootRow in rootLevelParents:
            if catRow[2] == rootRow[0]:
                secondLevelParents.append(catRow)

    # print("secondLevelParents", len(secondLevelParents))
    # print("=======TESTTTTTTTTTT================")
    # print(rootLevelParents
    # print("=======TESTTTTTTTTTT================")
    # print(secondLevelParents))
    return (rootLevelParents, secondLevelParents)


def getCatProd(catId):
    wcapi = API(
        url=fetched_data['url'],
        consumer_key=fetched_data['consumer_key'],
        consumer_secret=fetched_data['consumer_secret'],
        version=fetched_data['version']
    )

    prodResp = wcapi.get(
        "products?category={}&per_page=100".format(catId))

    # print("===== prodresp headers===")
    # for el in prodResp.headers:
    #     print(el)

    totalProd = int(prodResp.headers['X-WP-Total'])
    totalPages = int(prodResp.headers['X-WP-TotalPages'])

    # with open("jsonData3706.json", 'w') as outFile:
    #     json.dump(prodResp.json(), outFile)

    variableProducts = {}  # (id, name, link)
    # (id, name, regular_price, sale_price, curr_date date_mod, parent_id)
    variationProducts = {}
    # (id, name, regular_price, sale_price, curr_price, date_mod)
    simpleProducts = {}

    nextPage = 1
    while(nextPage <= totalPages and prodResp.status_code == 200):
        for prod in prodResp.json():
            if prod['type'] == 'variable':
                # print("having variations")
                # display in accordion
                # print(prod['id'], prod['name'])
                variableProducts[prod['id']] = {
                    'name': prod['name'],
                    'permalink': prod['permalink']
                }
                # variableProducts.append(
                #     (prod['id'], prod['name'], prod['permalink']))
                variationResp = wcapi.get(
                    "products/{}/variations?per_page=100".format(prod['id']))
                totalVariations = int(
                    variationResp.headers['X-WP-Total'])
                # print("Variations dir from resp =>", totalVariations)
                for variation in variationResp.json():
                    # print(variation['id'], variation['attributes'])
                    variationProducts[variation['id']] = {
                        'name': prod['name'],
                        'permalink': variation['permalink'],
                        'attributes': variation['attributes'],
                        'regular_price': variation['regular_price'],
                        'sale_price': variation['sale_price'],
                        # 'curr_price': variation['price'],
                        'date_modified': variation['date_modified'],
                        'parent': prod['id']
                    }
                    # print("PERMALINK TEST- ",
                    #       variationProducts[variation['id']]['permalink'])

                # print("attribute check",
                #       variationProducts[variation['id']]['attributes'])
                # variationProducts.append((variation['id'], prod['name'], variation['attributes'],
                #                           variation['regular_price'],
                #                           variation['sale_price'], variation['date_modified'], prod['id']))
            # product without variables or variations
            elif prod['type'] != 'variable' and 'name' in prod.keys():
                # get all products and display without accordion
                # print("not having variations")
                simpleProducts[prod['id']] = {
                    'name': prod['name'],
                    'permalink': prod['permalink'],
                    'regular_price': prod['regular_price'],
                    'sale_price': prod['sale_price'],
                    'price': prod['price'],
                    'date_modified': prod['date_modified'],
                    'parent': 0
                }
                # simpleProducts.append((prod['id'], prod['name'], prod['regular_price'],
                #                        prod['sale_price'], prod['date_modified']))

tasks/new_task/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.views import View
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.urls import reverse
from tasks.models import Task

# Create your views here.


@method_decorator(login_required, name="dispatch")
class NewTask(View):
    def get(self, request):
        tl_list = list(User.objects.filter(
            groups__name='Team Leader - CS department'))
        tm_list = list(User.objects.filter(
            groups__name='Team Member - CS department'))
        users = tl_list + tm_list
        context = {
            'users': users
        }

        return render(request, "new-task.html", context)

    def post(self, request):
        # save the new task in DB

        given_to = User.objects.get(username=request.POST["given_to"])
        given_by = request.user
        task_date = request.POST["task_date"]
        deadline = request.POST["task_deadline"]

        task = Task.objects.create(
            given_to=given_to,
            given_by=given_by,
            task_date=task_date,
            deadline=deadline
        )
        task.save()

        return redirect(reverse('tasks:add-products', args=[task.id]))

tasks/review_task/views.py
from django.shortcuts import render, HttpResponse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from tasks.models import Task, Product
from django.views import View
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.


@method_decorator(login_required, name="dispatch")
class ReviewTask(View):

    def get(self, request, taskid):
        try:
            task = Task.objects.get(pk=taskid)
            # only person who has given the task can review it
            if request.user == task.given_by:
                if task.status == Task.NEW or task.status == Task.IN_PROGRESS:
                    return HttpResponse("Task is not ready to be reviewed!!", 404)
                else:
                    # if task.status == Task.READY_TO_REVIEW:
                    products = Product.objects.filter(task_id=task)

                    for i in range(len(products)):
                        if products[i].status == Product.APPROVED or products[i] == Product.REJECTED:
                            continue
                        else:
                            # print("one is not reviewed")
                            break
                        # if all the products are reviewed i.e. break statement has not been executed
                    else:
                        # print("if all the products are reviewed -")
                        task.status = Task.READY_TO_UPLOAD
                        task.save()

                    context = {
                        "task": task,
                        "products": products
                    }
                    return render(request, "task-review.html", context)
                # return HttpResponse("Task has already been reviewed!!", 404)
            return HttpResponse("You cannot review task given by other person!!", 401)

        except ObjectDoesNotExist:
            return HttpResponse("Product not found", 404)

    def post(self, request, taskid):
        try:
            task_id = request.POST.get("task_id")
            task = Task.objects.get(pk=task_id)
            product_id = request.POST.get("product_id")
            product = Product.objects.get(
                product_id=product_id, task_id_id=task.id)
            # only person who has given the task can review it
            if request.user == task.given_by:
                if task.status == Task.READY_TO_REVIEW:
                    submitter_btn = request.POST.get("submitter_btn")
                    if submitter_btn == "approve_btn":
                        product.status = Product.APPROVED
                        product.save()

                    elif submitter_btn == "reject_btn":
                        product.status = Product.REJECTED
                        product.save()

                    return HttpResponse("successfully marked as - {}".format(product.status), 200)
                return HttpResponse("you cannot review already reviewed task", 405)
            else:
                return HttpResponse("You cannot review task given by other person!!", 401)
        except ObjectDoesNotExist as e:
            return HttpResponse(e, 404)

        return HttpResponse("post req", 200)


def changeStatus(request, taskid):
    if request.method == "POST":
        task_id = request.POST.get("task_id")
        try:
            task = Task.objects.get(pk=task_id)
            if request.user == task.given_by:
                submitter_btn = request.POST.get("submitter_btn")
                if submitter_btn == "task_ready_to_upload_btn":
                    task.status = Task.READY_TO_UPLOAD
                    task.save()
                elif submitter_btn == "task_cancelled_btn":
                    task.status = Task.CANCELLED
                    task.save()
                return HttpResponse("task marked as - {}".format(task.status), 200)
            else:
                return HttpResponse("You cannot review task given by other person!!", 401)
        except ObjectDoesNotExist:
            return HttpResponse("Task does not exists", 404)

tasks/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %}
    {% endblock head %}
</head>
<body>
    {% block content %}
    {% endblock content %}
    
</body>
</html>

tasks/templates/display-prod-wcheck.html
<!-- #for adding the products -->
<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-heading">Products </div>
        <div class="panel-body" id="no-cat-msg">
            {% if variableProducts|length > 0 or simpleProducts|length > 0 %}
            <form role="form" id="assign-prod-form" method="POST" action="">
                {% csrf_token %}
                
                <div class="col-md-12" id="add-prod-btn">
                    <button type="submit" class="btn btn-success pull-right">Add Products to task</button>
                </div>
                <div class="mg-10"> </div>
                <!-- variable products -->
                {% include "variables-with-check.html" %}
                <br/>
                <!-- simple products -->
                {% include "simples-with-check.html" %}
            </form>
            {% else %}
            <div class="alert alert-warning" role="alert">No products in this category!</div>
            {% endif %}
        </div>
    </div><!-- /.panel-->
</div><!-- /.col-->

tasks/templates/prod-view-del.html
{% if products|length > 0 %}
<table class="table table-striped">
    <tr>
        <th>Product ID</th>
        <th class="col-md-4"> Name</th>
        <th> Regular Price</th>
        {% if user == task.given_to %}
        <th> New regular Price</th>
        {% endif %}
        <!-- <th> eYeMobiles/ Current Price</th> -->
        <th> Sale Price</th>
        {% if user == task.given_to %}
        <th> Suggested Price</th>
        {% endif %}
        {% if user == task.given_by and task.status == "new" %}
        <th> Delete Product</th>
        {% endif %}

    </tr>
    {% for product in products %}
    <tr>
        <td>
            {% if product.permalink != None and product.permalink != "null" %}
            <a href="{{product.permalink}}" target="_blank">
            {% endif %}
            {{product.product_id}}
            {% if product.permalink != None %}</a>{% endif %}
        </td>
        <td>{{product.name}}</td>
        <td>{{product.regular_price}}</td>
        {% if user == task.given_to %}
        <td>{{product.new_reg_price}}</td>
        {% endif %}
        <!-- <td>{{product.curr_price}}</td> -->
        <td>{{product.sale_price}}</td>
        {% if user == task.given_to %}
        <td>{{product.suggested_price}}</td>
        {% endif %}
        {% if user == task.given_by and task.status == "new" %}
        <td>
            <form method="POST" action="{% url 'tasks:delete-product' %}" class="delete-form">
                {% csrf_token %}
            
                <input type="hidden" name="product_id" value="{{product.product_id}}" />
                <input type="hidden" name="task_id" value="{{product.task_id_id}}" />
                <button type="submit" class="btn btn-danger" id="{{product.product_id}}_btn" >
                    <i class="fa fa-trash"></i>
                </button>

            </form>
        </td>
        {% endif %}
        
    </tr>
    {% endfor %}
</table>
{% else %}
<div class="alert alert-warning" role="alert">No products in this category!</div>
{% endif %}

tasks/templates/sidebar.html
<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
    <div class="profile-sidebar">
        <div class="profile-userpic">
            <img src="http://placehold.it/50/30a5ff/fff" class="img-responsive" alt="">
        </div>
        <div class="profile-usertitle">
            <div class="profile-usertitle-name">{{user.first_name}} {{user.last_name.0}}.</div>
            <div class="profile-usertitle-status"><span class="indicator label-success"></span>Online</div>
        </div>
        <div class="clear"></div>
    </div>
    <div class="divider"></div>
    <!-- <form role="search">
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
        </div>
    </form> -->
    <ul class="nav menu">
        <!-- <li><a href="index.html"><em class="fa fa-dashboard">&nbsp;</em> Dashboard</a></li>
        <li><a href="products.html"><em class="fa fa-pencil-square-o">&nbsp;</em> Price Update</a></li>
        <li><a href="obsolete.html"><em class="fa fa-ban">&nbsp;</em> Obsolete Products</a></li> -->
        <li><a href="{% url 'tasks:task-list' %}"><em class="fa fa-file">&nbsp;</em> Task</a></li>
        <!-- <li><a href="push.html"><em class="fa fa-upload">&nbsp;</em> Push Products to Web</a></li>
        <li><a href="report.html"><em class="fa fa-bar-chart">&nbsp;</em> Report</a></li> -->
        <li><a href="{% url 'authz:logout' %}"><em class="fa fa-power-off">&nbsp;</em> Logout</a></li>
    </ul>
</div>
<!--/.sidebar-->

tasks/templates/task-review.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Price Update | EyeMobiles - CRM</title>
	{% include "headtags.html" %}
</head>
<body>
	{% include "navbar.html" %}
	{% include "sidebar.html" %}
		
	<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
		<div class="row">
			<ol class="breadcrumb">
				<li><a href="#">
					<em class="fa fa-home"></em>
				</a></li>
				<li class="active">Task Review</li>
			</ol>
		</div><!--/.row-->
		
		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Task Review - {{task.id}}</h1>
				<div>
					<table id="task-details-table">
				
						<tr>
							<th>
								Given by:
							</th>
							<td> {{task.given_by}}</td>
							<th>
								Status:
							</th>
							<td> {{task.status}}</td>
							<th>
								Deadline:
							</th>
							<td> {{task.deadline}}</td>
							<th>
								Created on:
							</th>
							<td> {{task.date_created}}</td>
							
						</tr>
					</table>
				</div>
			</div>
			
			<form mehtod="POST" action="{% url 'tasks:change-status' taskid=task.id %}"
				id="change-status-form" class="change-status-form">
				<input type="hidden" name="task_id" value="{{task.id}}" />
				<div class="pull-left col-md-3">
					{% if task.status == "approved" or task.status == "rejected" or task.status == "ready_to_upload" or task.status == "cancelled" %}
					<div class="btn btn-success mg-10" disabled>
						task status - {{task.status}}
					</div>
					{% else %}
					<button id="task_ready_to_upload_btn" name="task_ready_to_upload_btn"
						class="btn btn-success mg-10">
						Mark as Ready to Upload
					</button>
					{% endif %}
				</div>
				{% if task.status == "approved" or task.status == "rejected" or task.status == "ready_to_upload" or task.status == "cancelled" %}
				{% else %}
				<div class="pull-left col-md-2">
					<button id="task_cancelled_btn" name="task_cancelled_btn"
						class="btn btn-danger mg-10">
						Mark as Cancelled
					</button>
				</div>
				{% endif %}
			</form>
		</div><!--/.row-->
				
		<div class="row">
			
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">Products - {{task.given_to}} - {{task.deadline}}</div>
					<div class="panel-body">
					<!-- <button type="submit" class="btn btn-primary">Approve All Products</button> -->

					<div class="mg-10"> </div>
					<div class="col-md-12">
						{% if products|length > 0 %}
						<div class="table-responsive">
							<table class="table table-striped ">
								<tr>
									<th>ID</th>
									<th class="col-md-4">Name</th>
									<th> Regular Price</th>
									<th style="background-color: #c5fcaf;"> New Regular Price</th>
									<!-- <th> eYeMobiles Price</th> -->
									<th> Sale Price</th>
									<th style="background-color: #c5fcaf;"> Suggested Price</th>
									<th> Sharaf DG</th>
									<th> Carrefour</th>
									<th> Jumbo</th>
									<th> LuLu</th>
									<th> Axiom</th>
									<th> Approve/ reject Product</th>
								</tr>
								{% for product in products %}
								<tr class="{{product.product_id}}">
						
									<td>
										{% if product.permalink != None and product.permalink != "" %}
										<a href="{{product.permalink}}">
										{% endif %}
										{{product.product_id}}
										{% if product.permalink != None and product.permalink != "" %}</a>{% endif %}
									</td>
									<td class="col-md-4">{{product.name}}
									</td>
									<td>{{product.regular_price}}</td>
									<td style="background-color: #c5fcaf;">
										{{product.new_reg_price}}
									</td>
									<!-- <td>{{product.curr_price}}</td> -->
									<td>{{product.sale_price}}</td>
									<td style="background-color: #c5fcaf;">{{product.suggested_price}}</td>
									<td>
										{% if product.sharaf_dg_product_link != None and product.sharaf_dg_product_link != "" %}
										<a href="{{product.sharaf_dg_product_link}}">
										{% endif %}
										{{product.sharaf_dg_price}}
										{% if product.sharaf_dg_product_link != None and product.sharaf_dg_product_link != "" %}</a>{% endif %}
									</td>
									<td>
										{% if product.carrefour_product_link != None and product.carrefour_product_link != "" %}
										<a href="{{product.carrefour_product_link}}">
										{% endif %}
										{{product.carrefour_price}}
										{% if product.carrefour_product_link != None and product.carrefour_product_link != "" %}</a>{% endif %}
									</td>
									<td>
										{% if product.jumbo_product_link != None and product.jumbo_product_link != "" %}
										<a href="{{product.jumbo_product_link}}">
										{% endif %}
										{{product.jumbo_price}}
										{% if product.jumbo_product_link != None and product.jumbo_product_link != "" %}</a>{% endif %}
									</td>
									<td>
										{% if product.lulu_product_link != None and product.lulu_product_link != "" %}
										<a href="{{product.lulu_product_link}}">
										{% endif %}
										{{product.lulu_price}}
										{% if product.lulu_product_link != None and product.lulu_product_link != "" %}</a>{% endif %}
									</td>
									<td>
										{% if product.jumbo_product_link != None and product.jumbo_product_link != "" %}
										<a href="{{product.jumbo_product_link}}">
										{% endif %}
										{{product.axiom_price}}
										{% if product.jumbo_product_link != None and product.jumbo_product_link != "" %}</a>{% endif %}
									</td>
									<td>
										{% if product.status == "not_reviewed" %}
										<form method="POST" action="{% url 'tasks:review-task' taskid=product.task_id.id %}"
											class="review-form">
											{% csrf_token %}
											<input type="hidden" name="product_id" value="{{product.product_id}}" />
											<input type="hidden" name="task_id" value="{{product.task_id_id}}" />
											
											<button type="submit" name="approve_btn" class="btn btn-link" id="approve-btn">
												<i class="fa fa-check" style="color: rgb(10, 240, 10);"></i>
											</button>
											<!-- <input type="submit" name="approve-btn" class="btn btn-link" id="approve-btn"
												value="approve" /> -->
								
											
											<button type="submit" name="reject_btn" class="btn btn-link" id="reject-btn">
												<i class="fa fa-times" style="color: red;"></i>
											</button>
											<!-- <input type="submit" name="reject-btn" class="btn btn-link" id="reject-btn"
												value="reject" /> -->
										</form>
										{% elif product.status == "uploaded" or product.status == "approved" %}
										<i class="fa fa-check" style="color: rgb(10, 240, 10);"></i>
										{% elif product.status == "rejected" %}
										<i class="fa fa-times" style="color: red;"></i>
										{% endif %}
									</td>
								</tr>
								{% endfor %}
							</table>
						</div>
						{% endif %}
					</div>
					
				</div><!-- /.panel-->
			</div><!-- /.col-->
		</div>
			<div class="col-sm-12">
				<p class="back-link">CRM BY - Development Department</p>
			</div>
		</div><!-- /.row -->
	</div><!--/.main-->
	
{% include "scripts-include.html" %}
<script src="{% static 'js/task-review.js' %}"></script>

</body>
</html>

tasks/templates/task-table.html
{% if tasks|length > 0 %}
  

<table class="table table-striped" id="task-table">
    <tr>
        <th> Task ID</th>
        <th> Given to</th>
        <th> Total Number of products</th>
        <th> Task Date</th>
        {% if tasks.0.status == "new" or tasks.0.status == "in_progress" or tasks.0.status == "ready_to_review" %}
       
        {% else %}
        <th> Approved</th>
        <th> Rejected</th>
        {% endif %}
        <th> Deadline</th>
        {% if tasks.0.status == "ready_to_review" %}
        <th> Review</th>
        {% endif %}
        
    </tr>
    {% for task in tasks %}
    <tr>
        <td><a href="{% url 'tasks:task' taskid=task.id %}">{{task.id}}</a></td>
        <td>{{task.given_to}}</td>
        <td>{{task.num_of_products}}</td>
        <td>{{task.task_date}}</td>
        {% if tasks.0.status == "new" or tasks.0.status == "in_progress" or tasks.0.status == "ready_to_review" %}
        
        {% else %}
        <td>{{task.num_of_approved_products}}</td>
        <td>{{task.num_of_rejected_products}}</td>
        {% endif %}
        <td>{{task.deadline}}</td>
        {% if tasks.0.status == "ready_to_review" %}
        <td><a href="{% url 'tasks:review-task' taskid=task.id %}"><i class="fa fa-eye"></i></a></td>
        {% endif %}
        

    </tr>
    {% endfor %}
</table>
{% else %}
<div class="alert alert-warning" role="alert">
    No tasks here!
</div>
{% endif %}